### ISSUE TITLE
STMicroelectronics AI software

### ISSUE THREAD

**Issue by fkromer** [Bisonai/awesome-edge-machine-learning#2]
STMicroelectronics provides some nice AI software expansion packages. There is no suitable section yet. Probably it's worth adding a new section "MCU software packages", "MPU software packages" or something like this.

- [STM32Cube](https://www.st.com/content/st_com/en/stm32cube-ecosystem.html) compatible extension packages
  - [FP-AI-Sensing](https://www.st.com/content/st_com/en/products/embedded-software/mcu-mpu-embedded-software/stm32-embedded-software/stm32-ode-function-pack-sw/fp-ai-sensing1.html) -  STM32Cube function pack for ultra-low power IoT node with artificial intelligence (AI) application based on audio and motion sensing.
  - [FP-AI-VISION1](https://www.st.com/content/st_com/en/products/embedded-software/mcu-mpu-embedded-software/stm32-embedded-software/stm32cube-expansion-packages/fp-ai-vision1.html) - STM32Cube function pack for high performance STM32 with artificial intelligence (AI) application for Computer Vision.
- [OpenSTLinux](https://www.st.com/content/st_com/en/products/embedded-software/mcu-mpu-embedded-software/stm32-embedded-software/stm32-mpu-openstlinux-distribution.html) compatible extension packages
  - [X-LINUX-AI-CV](https://www.st.com/content/st_com/en/products/embedded-software/mcu-mpu-embedded-software/stm32-embedded-software/stm32-mpu-openstlinux-expansion-packages/x-linux-ai-cv.html) - STM32 MPU OpenSTLinux Expansion Pack for AI computer vision application.

**Comment by martinkersner** [comment]
Hi @fkromer ! Thank you for contributing! I created a new section MCU and MPU software packages. https://github.com/Bisonai/awesome-edge-machine-learning#mcu-and-mpu-software-packages
