### ISSUE TITLE
NXP AI software

### ISSUE THREAD

**Issue by fkromer** [Bisonai/awesome-edge-machine-learning#3]
NXP software packages which don't fit in the sections existing.

- Software development tools
  - [eIQ ML Software Development Environment](https://www.nxp.com/design/software/development-software/eiq-ml-development-environment:EIQ)
  - [eIQ Auto deep learning (DL) toolkit](https://www.nxp.com/design/software/development-software/eiq-auto-dl-toolkit:EIQ-AUTO)
- Inference Engines supported
   - [Arm NN Inference Engine](https://www.nxp.com/design/software/development-software/eiq-ml-development-environment/eiq-software-for-arm-nn-inference-engine:eIQArmNN)
  - [TensorFlow Lite](https://www.nxp.com/design/software/development-software/eiq-ml-development-environment/eiq-for-tensorflow-lite:eIQTensorFlowLite)
  - [Glow](https://www.nxp.com/design/software/development-software/eiq-ml-development-environment/eiq-for-glow-neural-network-compiler:eIQ-Glow)
  - [Arm CMSIS-NN](https://www.nxp.com/design/software/development-software/eiq-ml-development-environment/eiq-for-arm-cmsis-nn:eIQArmCMSISNN)

**Comment by martinkersner** [comment]
Hi @fkromer ! Thank you for contributing! I created a new section MCU and MPU software packages. https://github.com/Bisonai/awesome-edge-machine-learning#mcu-and-mpu-software-packages
