### ISSUE TITLE
Texas Instruments AI software

### ISSUE THREAD

**Issue by fkromer** [Bisonai/awesome-edge-machine-learning#4]
- [Processor SDK Linux for AM57x](www.ti.com/tool/SITARA-MACHINE-LEARNING) - Part of Sitara Machine Learning suite. Contains the TI Deep Learning (TIDL) software framework. Supports ArmNN.

**Comment by martinkersner** [comment]
Hi @fkromer ! Thank you for contributing! I created a new section MCU and MPU software packages. https://github.com/Bisonai/awesome-edge-machine-learning#mcu-and-mpu-software-packages
